# Proxy server
server:
username:
password:
port:

# RSS feed
target_urls:
  - https://news.google.com/rss?hl=ja&gl=JP&ceid=JP%3Aja&oc=11
ignore_words:
  - "Google ニュースですべての記事を見る"
ignore_domains:
  - www.google.com

# Incoming WebHooks
webhook_url:
