# Proxy server
server: https://news.google.com/rss?hl=ja&gl=JP&ceid=JP%3Aja&oc=11
username:
password:
port:

# RSS feed
target_url: https://news.google.com/rss?hl=ja&gl=JP&ceid=JP%3Aja&oc=11
ignore_words:
  - "Google ニュースですべての記事を見る"
ignore_domains:
  - f1-gate.com
  - jp.motorsport.com
  - nikkansports.com
  - www.nikkansports.com
  - hochi.news
  - news.golfdigest.co.jp

# Incoming WebHooks
webhook_url: